enum tnumber { TEOF, TCONST, TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TEQUAL, TNOTEQU, TLESSE, TGREATE, TAND,
        TOR, TINC, TDEC, TASSIGN, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TIDENT, TCOMMENT, TNUMBER,
        TSEMICOLON, TPLUS, TMINUS, TSTAR, TMOD, TSLASH, TNOT, TLESS, TGREAT, TRSBRACKET, TLSBRACKET, TCOMMA,
        TRMBRACKET, TLMBRACKET,TRLBRACKET, TLLBRACKET, TSEPARATOR, TLINE, TILLID, TERROR };

enum errorTypes { noerror, illsp, illid, overst, illlen, wrongid };